// generated by tools-cli/generate-manifest.mjs -- do not edit by hand.
//
// Typed parameter shapes for each Virtual SDK method derived from the
// committed operation manifest.

export interface Params_activate_api_token {
  "apiTokenId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_attach_merchant_account {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
  /** The merchant account id to attach at the respective entity level. */
  "merchantAccountId"?: string;
  /** List of bin ranges (6 or 8 digits) separated by semicolons. */
  "binRangeLimit"?: string;
  /** List of country codes separated by semicolons. */
  "binCountryLimit"?: string;
  /** List of brands comma-separated. */
  "subTypes"?: string;
  /** The currency. No list of currencies supported. */
  "currency"?: string;
  /** Allow transactions with unrecognizable BIN to process with this merchant account. */
  "processTransactionsWithoutBinIdentification"?: boolean;
  /** The dynamic descriptor for a better bank statement.  */
  "customDescriptor1"?: string;
  /** CHANNEL_NAME”, “MERCHANT_NAME”, “USAGE”, “TRANSACTION_ID”, “INVOICE_ID”, “SHORT_ID”, “INV”, “INVC”, “Re”, “Rech”, “Renr”, “RNr”, “R.-Nr */
  "selectionDescriptor1"?: string;
  /** The dynamic descriptor for a better bank statement. */
  "customDescriptor2"?: string;
  /** “CHANNEL_NAME”, “MERCHANT_NAME”, “USAGE”, “TRANSACTION_ID”, “INVOICE_ID”, “SHORT_ID” */
  "selectionDescriptor2"?: string;
  /** The dynamic descriptor for a better bank statement. */
  "customDescriptor3"?: string;
  /** “CHANNEL_NAME”, “MERCHANT_NAME”, “USAGE”, “TRANSACTION_ID”, “INVOICE_ID”, “SHORT_ID” */
  "selectionDescriptor3"?: string;
}

export interface Params_create_api_token {
  "merchantId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_create_channel {
  "merchantId": string;
  /** The name of the channel. */
  "name": string;
  /** LIVE, CONNECTOR_TEST, INTEGRATOR_TEST, DISABLED */
  "state": string;
  /** The customer identifier. */
  "customerId"?: string;
  /** The description of the channel entity. */
  "description"?: string;
}

export interface Params_create_contact {
  parentType: "psp" | "division" | "merchant";
  parentId: string;
  /** The user corporate email address */
  "email"?: string;
  /** The first and last name */
  "name": string;
  /** The role of the account. Could be: */
  "role"?: string;
  /** The kind of the created contact. Could be: */
  "kind"?: string;
  /** The contact language should be a two-letter code. The available values are: */
  "language"?: string;
  /** The mobile phone number */
  "mobile"?: string;
  /** Automatically attach the user to the same entity. */
  "autoAttach"?: boolean;
  /** The contact description */
  "description"?: string;
  /** Required for OAUTH kind contacts (BIP, developer portal, virtual terminal) */
  "oauthRedirectUrl"?: string;
  /** Send an email upon contact creation. */
  "sendCredentialsMail"?: boolean;
  /** Send authenticator email upon contact creation. */
  "sendAuthenticatorMail"?: boolean;
}

export interface Params_create_division {
  "pspId": string;
  /** The name of the division. */
  "name": string;
  /** LIVE, CONNECTOR_TEST, INTEGRATOR_TEST, DISABLED */
  "state": string;
  /** The customer identifier. */
  "customerId"?: string;
  /** The description of the division entity. */
  "description"?: string;
}

export interface Params_create_merchant {
  "divisionId": string;
  /** The name of the merchant. */
  "name": string;
  /** LIVE, CONNECTOR_TEST, INTEGRATOR_TEST, DISABLED */
  "state": string;
  /** The customer identifier. */
  "customerId"?: string;
  /** The description of the merchant entity. */
  "description"?: string;
}

export interface Params_create_merchant_account {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
  /** The merchant account name. */
  "name": string;
  /** The merchant Account state. LIVE, CLOSED, TEST or DISABLED. */
  "state": string;
  /** The acquirer or alternative payment method name. */
  "clearingInstituteName"?: string;
  /** The MID (Merchant Identifier). */
  "merchantId"?: string;
  "key": string;
  /** The acquirer or alternative payment method specific parameter. */
  "connectorSpecificParameter.MerchantKeyId"?: string;
  /** The merchant IBAN for funds to be transferred (SEPA). */
  "iban"?: string;
  /** OR The id of the acquirer or alternative payment method. */
  "cleaingInstituteId"?: string;
  /** The card acceptor terminal id. */
  "terminalId"?: string;
  /** The credentials use to connect to the provider. */
  "password"?: string;
  /** The credentials use to connect to the provider. */
  "username"?: string;
  /** RETAIL, SERVICES, AIRLINE, HOTEL, TRAVEL, GAMING, GAMBLING, DIGITAL_CONTENT, AUCTION, ADULT, UTILITIES, E_TICKETING or ONLINE_FINANCIAL */
  "merchantCategory"?: string;
  /** ANY, MOTO, ECOMMERCE, EWALLET */
  "transactionCategory"?: string;
  /** IGNORE, CHECK */
  "cvvInstruction"?: string;
  /** Auto-reverse the authorization depending on the rejection policy */
  "cvvRejectionPolicy"?: string;
  /** Auto-reverse the authorization depending on the address matching rule (TRUE or FALSE) */
  "avsCheckActive"?: string;
  /** Auto-reverse the authorization depending on the rejection policy */
  "avsRejectionPolicy"?: string;
  /** Mark transaction for review depending on the rejection policy (see above) */
  "avsReviewPolicy"?: string;
  /** Possible values are: DA or DD */
  "debitAdviceProcedure"?: string;
  /** NONE, RECURRING, INSTALLMENT */
  "recurringCode"?: string;
  /** TRUE. FALSE support for 3D Secure */
  "supports3DSecure": boolean;
  /** The merchant name (3DS2) */
  "merchant3DName": string;
  /** The merchant URL (3DS2) */
  "merchant3DUrl": string;
  /** The merchant country code (3DS2) */
  "merchantIsoCountryCode": number;
  /** The merchant ID (3DS2) */
  "merchant3DId": number;
  /** The merchant category code (3DS2) */
  "merchant3DCategory": number;
  /** The merchant acquirer bin for VISA (3DS2) */
  "visaMerchantAcquirerBin_v2": number;
  /** The reqestor id for VISA (3DS2) */
  "visaRequestorId_v2": number;
  /** The requestor name for VISA (3DS2) */
  "visaRequestorName": string;
  /** The merchant acquirer bin for MASTERCARD (3DS2) */
  "masterMerchantAcquirerBin_v2": number;
  /** The reqestor id for MASTERCARD (3DS2) */
  "masterRequestorId_v2": number;
  /** The requestor name for MASTERCARD (3DS2) */
  "masterRequestorName": string;
  /** The merchant acquirer bin for AMEX (3DS2) */
  "amexMerchantAcquirerBin_v2": number;
  /** The reqestor id for AMEX (3DS2) */
  "amexRequestorId_v2": string;
  /** The requestor name for AMEX (3DS2) */
  "amexRequestorName": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantId": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantPwd": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "dinersRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "dinersRequestorName": string;
  /** Required for 3D Secure v2.x */
  "bcmcMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "bcmcRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "bcmcRequestorName": string;
  /** Required for 3D Secure v2.x */
  "jcbMerchantAcquirerBin_v2"?: string;
  /** Required for 3D Secure v2.x */
  "jcbRequestorId_v2"?: string;
  /** Required for 3D Secure v2.x */
  "jcbRequestorName"?: string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaRequestorName": string;
  /** TRUE or FALSE */
  "velocityDispachingActive"?: string;
  /** {Maximum number of Tx};{Maximum volume};{within};{HOUR|DAY|WEEK|MONTH|YEAR} */
  "velocityDispatchingSetting"?: string;
  /** TRUE or FALSE */
  "ticketSizeDispatchingActive"?: string;
  /** {Minimum ticket size};{Maximum ticket size} */
  "ticketSizeDispatchingSetting"?: string;
  /** ALL: All shoppers */
  "recurringDispatchingSetting"?: string;
  /** ALL: All shoppers */
  "shopperDispatchingSetting"?: string;
  /** PSP, DIVISION, MERCHANT, OR CHANNEL */
  "shopperDispatchingScope"?: string;
  /** In days */
  "shopperDispatchingValidity"?: string;
  /** The dynamic timeout: minutes to wait the response from consumer before timing-out */
  "pendingTimeoutInMins"?: string;
  /** The dynamic timeout: minutes to wait the response from acquirer before timing-out */
  "pendingForAcquirerTimeoutInMins"?: string;
  /** The credentials use to upload files to the provider. */
  "uploadUser"?: string;
  /** The credentials use to upload files to the provider. */
  "uploadPassword"?: string;
}

export interface Params_delete_api_token {
  "apiTokenId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_delete_contact {
  "contactId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_delete_entity {
  parentType: "division" | "merchant" | "channel";
  parentId: string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_delete_merchant_account {
  "merchantAccountId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_detach_contact {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
  "contactId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_detach_merchant_account {
  "attachedMerchantAccountId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_edit_contact {
  "contactId": string;
  /** The user corporate email address */
  "email"?: string;
  /** The first and last name */
  "name": string;
  /** The role of the account. Could be: */
  "role"?: string;
  /** The kind of the created contact. Could be: */
  "kind"?: string;
  /** The contact language should be a two-letter code. The available values are: */
  "language"?: string;
  /** The mobile phone number */
  "mobile"?: string;
  /** Automatically attach the user to the same entity. */
  "autoAttach"?: boolean;
  /** The contact description */
  "description"?: string;
  /** Required for OAUTH kind contacts (BIP, developer portal, virtual terminal) */
  "oauthRedirectUrl"?: string;
  /** Send an email upon contact creation. */
  "sendCredentialsMail"?: boolean;
  /** Send authenticator email upon contact creation. */
  "sendAuthenticatorMail"?: boolean;
  /** The current state of the contact. Could be: */
  "state": string;
}

export interface Params_edit_entity {
  parentType: "division" | "merchant" | "channel";
  parentId: string;
  /** The name of the division. */
  "name": string;
  /** LIVE, CONNECTOR_TEST, INTEGRATOR_TEST, DISABLED */
  "state": string;
  /** The customer identifier. */
  "customerId"?: string;
  /** The description of the division entity. */
  "description"?: string;
}

export interface Params_edit_merchant_account {
  "merchantAccountId": string;
  /** Enable 3DS2 on your merchant account. */
  "supports3DSecure": boolean;
  /** The merchant name. */
  "merchant3DName": string;
  /** The merchant website URL. */
  "merchant3DUrl": string;
  /** Merchant ISO country code. 276 is Germany. */
  "merchantIsoCountryCode": number;
  /** Merchant identifier */
  "merchant3DId": number;
  /** The Merchant category code */
  "merchant3DCategory": number;
  /** The Visa acquirer BIN (3DS2). */
  "visaMerchantAcquirerBin_v2": number;
  /** The Visa requestor id (3DS2). */
  "visaRequestorId_v2": number;
  /** The Visa requestor name (3DS2). */
  "visaRequestorName": string;
  /** The MasterCard acquirer BIN (3DS2). */
  "masterMerchantAcquirerBin_v2": number;
  /** The MasterCard requestor id (3DS2). */
  "masterRequestorId_v2": number;
  /** The MasterCard requestor name (3DS2). */
  "masterRequestorName": string;
  /** The AMEX acquirer BIN (3DS2). */
  "amexMerchantAcquirerBin_v2": number;
  /** The AMEX requestor id (3DS2). */
  "amexRequestorId_v2": string;
  /** The AMEX requestor name (3DS2). */
  "amexRequestorName": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantId": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantPwd": string;
  /** Required for 3D Secure v2.x */
  "dinersMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "dinersRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "dinersRequestorName": string;
  /** Required for 3D Secure v2.x */
  "bcmcMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "bcmcRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "bcmcRequestorName": string;
  /** Required for 3D Secure v2.x */
  "jcbMerchantAcquirerBin_v2"?: string;
  /** Required for 3D Secure v2.x */
  "jcbRequestorId_v2"?: string;
  /** Required for 3D Secure v2.x */
  "jcbRequestorName"?: string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaMerchantAcquirerBin_v2": string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaRequestorId_v2": string;
  /** Required for 3D Secure v2.x */
  "cashlinkMaltaRequestorName": string;
  /** The name of the merchant account. */
  "name": string;
  /** Possible values are "LIVE", "CLOSED", "TEST" or "DISABLED" */
  "state": string;
  "clearingInstituteName"?: string;
  "merchantId"?: string;
  "key": string;
  "connectorSpecificParameter.MerchantKeyId"?: string;
  "iban"?: string;
  "cleaingInstituteId"?: string;
  "terminalId"?: string;
  "password"?: string;
  "username"?: string;
  /** Possible values are: RETAIL, SERVICES, AIRLINE, HOTEL, TRAVEL, GAMING, GAMBLING, DIGITAL_CONTENT, AUCTION, ADULT, UTILITIES, E_TICKETING or ONLINE_FINANCIAL */
  "merchantCategory"?: string;
  /** Possible values are: ANY, MOTO, ECOMMERCE, EWALLET */
  "transactionCategory"?: string;
  "cvvInstruction"?: string;
  "cvvRejectionPolicy"?: string;
  /** TRUE or FALSE */
  "avsCheckActive"?: string;
  /** Possible values are: A, Z, N, U */
  "avsRejectionPolicy"?: string;
  /** Possible values are: A, Z, N, U */
  "avsReviewPolicy"?: string;
  /** Possible values are: DA or DD */
  "debitAdviceProcedure"?: string;
  /** Possible values are: NONE, RECURRING, INSTALLMENT */
  "recurringCode"?: string;
  /** TRUE or FALSE */
  "velocityDispachingActive"?: string;
  /** {Maximum number of Tx};{Maximum volume};{within};{HOUR|DAY|WEEK|MONTH|YEAR}For example, 12;11;2;DAY */
  "velocityDispatchingSetting"?: string;
  /** TRUE or FALSE */
  "ticketSizeDispatchingActive"?: string;
  /** {Minimum ticket size};{Maximum ticket size}For example, 2;10 */
  "ticketSizeDispatchingSetting"?: string;
  /** ALL: All shoppersTRUE: Recurring shoppersFALSE: First-time shoppers */
  "recurringDispatchingSetting"?: string;
  /** ALL: All shoppersTRUE: Recurring shoppersFALSE: First-time shoppers */
  "shopperDispatchingSetting"?: string;
  /** PSP, DIVISION, MERCHANT, or CHANNEL */
  "shopperDispatchingScope"?: string;
  /** in days */
  "shopperDispatchingValidity"?: string;
  /** Define time in minutes when this payment request from Consumer should timeout. */
  "pendingTimeoutInMins"?: string;
  /** Define time in minutes when the final payment status request from Acquirer should timeout. */
  "pendingForAcquirerTimeoutInMins"?: string;
  "uploadUser"?: string;
  "uploadPassword"?: string;
}

export interface Params_get_api_token {
  "apiTokenId": string;
}

export interface Params_get_contact {
  "contactId": string;
}

export interface Params_get_entity {
  parentType: "division" | "merchant" | "channel";
  parentId: string;
}

export interface Params_get_merchant_account {
  "merchantAccountId": string;
}

export interface Params_list_api_tokens {
  "merchantId": string;
}

export interface Params_list_attached_contacts {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
}

export interface Params_list_attached_merchant_accounts {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
}

export interface Params_list_channels {
  "merchantId": string;
}

export interface Params_list_clearing_institutes {
  "pspId": string;
}

export interface Params_list_divisions {
  "pspId": string;
}

export interface Params_list_merchants {
  "divisionId": string;
}

export interface Params_list_owned_contacts {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
}

export interface Params_list_owned_merchant_accounts {
  parentType: "psp" | "division" | "merchant" | "channel";
  parentId: string;
}

export interface Params_lock_contact {
  "contactId": string;
}

export interface Params_set_contact_password {
  "contactId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_suspend_api_token {
  "apiTokenId": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface Params_unlock_contact {
  "contactId": string;
}

export interface Params_update_api_token {
  "apiTokenId": string;
  /** The alias or display name of the API token. */
  "alias": string;
  /** Set true to bypass the confirm bridge for destructive calls. */
  confirm?: boolean;
}

export interface WebApiSdk {
  "activate_api_token"(params: Params_activate_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
  "attach_merchant_account"(params: Params_attach_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_api_token"(params: Params_create_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_channel"(params: Params_create_channel): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_contact"(params: Params_create_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_division"(params: Params_create_division): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_merchant"(params: Params_create_merchant): Promise<{ ok: boolean; status: number; data: unknown }>;
  "create_merchant_account"(params: Params_create_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "delete_api_token"(params: Params_delete_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
  "delete_contact"(params: Params_delete_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "delete_entity"(params: Params_delete_entity): Promise<{ ok: boolean; status: number; data: unknown }>;
  "delete_merchant_account"(params: Params_delete_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "detach_contact"(params: Params_detach_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "detach_merchant_account"(params: Params_detach_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "edit_contact"(params: Params_edit_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "edit_entity"(params: Params_edit_entity): Promise<{ ok: boolean; status: number; data: unknown }>;
  "edit_merchant_account"(params: Params_edit_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "get_api_token"(params: Params_get_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
  "get_contact"(params: Params_get_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "get_entity"(params: Params_get_entity): Promise<{ ok: boolean; status: number; data: unknown }>;
  "get_merchant_account"(params: Params_get_merchant_account): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_api_tokens"(params: Params_list_api_tokens): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_attached_contacts"(params: Params_list_attached_contacts): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_attached_merchant_accounts"(params: Params_list_attached_merchant_accounts): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_channels"(params: Params_list_channels): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_clearing_institutes"(params: Params_list_clearing_institutes): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_divisions"(params: Params_list_divisions): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_merchants"(params: Params_list_merchants): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_owned_contacts"(params: Params_list_owned_contacts): Promise<{ ok: boolean; status: number; data: unknown }>;
  "list_owned_merchant_accounts"(params: Params_list_owned_merchant_accounts): Promise<{ ok: boolean; status: number; data: unknown }>;
  "lock_contact"(params: Params_lock_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "set_contact_password"(params: Params_set_contact_password): Promise<{ ok: boolean; status: number; data: unknown }>;
  "suspend_api_token"(params: Params_suspend_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
  "unlock_contact"(params: Params_unlock_contact): Promise<{ ok: boolean; status: number; data: unknown }>;
  "update_api_token"(params: Params_update_api_token): Promise<{ ok: boolean; status: number; data: unknown }>;
}

declare const sdk: WebApiSdk;
export default sdk;
