// generated by tools-cli/generate-manifest.mjs -- do not edit by hand.

export type WebApiToolName =
  | "attach_merchant_account"
  | "create_channel"
  | "create_contact"
  | "create_division"
  | "create_merchant"
  | "create_merchant_account"
  | "delete_contact"
  | "delete_entity"
  | "delete_merchant_account"
  | "detach_contact"
  | "detach_merchant_account"
  | "edit_contact"
  | "edit_entity"
  | "get_contact"
  | "get_entity"
  | "get_merchant_account"
  | "list_attached_contacts"
  | "list_attached_merchant_accounts"
  | "list_channels"
  | "list_clearing_institutes"
  | "list_divisions"
  | "list_merchants"
  | "list_owned_contacts"
  | "list_owned_merchant_accounts"
  | "lock_contact"
  | "set_contact_password"
  | "unlock_contact"

export interface WebApiRequestField {
  name: string;
  logicalType: "string" | "boolean" | "enum" | "integer" | "url" | "timestamp_seconds";
  required: "required_path" | "required_spec" | "conditional" | "example_core" | "optional";
  description: string | null;
  pattern?: string;
  enum?: string[];
  format?: string;
  example?: unknown;
  conditionalTrigger?: { field: string; value: string };
  destructiveValues?: string[];
  provenance: string[];
}

export interface WebApiPathParam {
  name: string;
  pattern: string | null;
  required: true;
}

export interface WebApiOperation {
  operationId: string | null;
  toolName: WebApiToolName | null;
  parentEntityType: "psp" | "division" | "merchant" | "channel" | null;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  pathTemplate: string;
  pathParams: WebApiPathParam[];
  request: WebApiRequestField[];
  description: string | null;
  auditEventType: string | null;
  destructive: boolean;
}

export interface WebApiOperationManifest {
  schemaVersion: 1;
  generatedAt: string;
  source: { spec: string; mapping: string };
  tools: WebApiToolName[];
  toolIndex: Record<WebApiToolName, WebApiOperation[]>;
  operations: WebApiOperation[];
  unmappedOperationIds: string[];
}

declare const manifest: WebApiOperationManifest;
export default manifest;
