// generated by tools-cli/generate-manifest.mjs -- do not edit by hand.
//
// Audit event types emitted by operations in the bundled OpenAPI spec.
// Derived from manifest.operations[].auditEventType (sorted, deduplicated).
// Pure data; safe to import from main-world code.

export const AUDIT_EVENT_TYPES = [
  "contact_create",
  "contact_delete",
  "contact_detach",
  "contact_edit",
  "contact_lock",
  "contact_password_reset",
  "contact_unlock",
  "entity_create",
  "entity_delete",
  "entity_edit",
  "ma_attach",
  "ma_create",
  "ma_delete",
  "ma_detach",
  "ma_update",
] as const;

export type ApiAuditEventType = (typeof AUDIT_EVENT_TYPES)[number];
